version: '2'
services:
    leanagile-app:
        image: leanagile
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://leanagile-postgresql:5432/leanagile
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8090:8090
    leanagile-postgresql:
        extends:
            file: postgresql.yml
            service: leanagile-postgresql
